calculate:
  function: calculate/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: false
    final: true
rules-create:
  function: rules-create/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
rules-get:
  function: rules-get/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
rules-delete:
  function: rules-delete/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
rules-list:
  function: rules-list/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
webhook-quote-total:
  function: webhook-quote-total/index.js
  web: 'yes'
  runtime: nodejs:22
  require-adobe-auth: false
  annotations:
    require-adobe-auth: false
    final: false
  inputs:
    LOG_LEVEL: debug
